WITH SB AS (
    SELECT 
        H.HISTORY_ID,
        C.CAR_TYPE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
        C.DAILY_FEE,
        CASE 
            WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 THEN '7일 이상'
        END AS DURATION_GRP
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT 
    SB.HISTORY_ID,
    ROUND(SB.PERIOD * SB.DAILY_FEE * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM SB
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON SB.CAR_TYPE = P.CAR_TYPE
    AND SB.DURATION_GRP = P.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;