CREATE DATABASE programmers_join;
USE programmers_join;

CREATE TABLE PRODUCT (
	PRODUCT_ID INTEGER PRIMARY KEY NOT NULL,
	PRODUCT_CODE VARCHAR(8) NOT NULL,
    PRICE INTEGER NOT NULL
);

CREATE TABLE OFFLINE_SALE (
	OFFLINE_SALE_ID INTEGER PRIMARY KEY NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    SALES_AMOUNT INTEGER NOT NULL,
    SALES_DATE DATE NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

SHOW TABLES;

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRICE) VALUES 
(1, 'A1000011', 15000),
(2, 'A1000045', 8000),
(3, 'C3000002', 42000);

INSERT INTO OFFLINE_SALE (OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE) VALUES
(1, 1, 2, '2022-02-21'),
(2, 1, 2, '2022-03-02'),
(3, 3, 3, '2022-05-01'),
(4, 2, 1, '2022-05-24'),
(5, 1, 2, '2022-07-14'),
(6, 2, 1, '2022-09-22');

SELECT * FROM PRODUCT;

SELECT * FROM OFFLINE_SALE;

SELECT 
    PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM
    PRODUCT
        JOIN
    OFFLINE_SALE USING (PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC , PRODUCT_CODE ASC;
	




