USE programmers_join;

CREATE TABLE BOOK (
	BOOK_ID INTEGER PRIMARY KEY NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PRICE INTEGER NOT NULL,
    PUBLISHED_DATE DATE NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

CREATE TABLE AUTHOR (
	AUTHOR_ID INTEGER PRIMARY KEY NOT NULL,
    AUTHOR_NAME VARCHAR(20) NOT NULL
);

SHOW TABLES;

INSERT INTO BOOK (BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE) VALUES
(1, '인문', 1, 10000, '2020-01-01'),
(2, '경제', 1, 9000, '2021-04-11'),
(3, '경제', 2, 11000, '2021-02-05');

INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES 
(1, '홍길동'),
(2, '김영호');

SELECT * FROM BOOK;

SELECT * FROM AUTHOR;

SELECT 
    BOOK_ID,
    AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK
        JOIN
    AUTHOR USING (AUTHOR_ID)
WHERE
    CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;
	