USE programmers_join;

WITH TEMP AS (
	SELECT 
		A.CAR_ID, 
		A.CAR_TYPE,
		A.DAILY_FEE
	FROM CAR_RENTAL_COMPANY_CAR A 
	JOIN ( 
		SELECT 
			CAR_ID
		FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
		GROUP BY CAR_ID 
		HAVING MAX(END_DATE) <= '2022-11-01'
	)  AS B USING (CAR_ID)
	WHERE A.CAR_TYPE IN ('세단','SUV')
)

SELECT 
	B.CAR_ID,
    A.CAR_TYPE, 
    ROUND(B.DAILY_FEE * (1-A.DISCOUNT_RATE*0.01)*30) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS A
INNER JOIN TEMP B ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE LIKE '%30%'         
AND B.DAILY_FEE * (1-A.DISCOUNT_RATE*0.01)*30 BETWEEN '500000' AND '2000000'
ORDER BY 3 DESC, 2 ASC, 1 DESC