CREATE DATABASE programmers_mockTest;
SHOW DATABASES;

USE programmers_mockTest;

CREATE TABLE OLD_POSTS (
	ID INT PRIMARY KEY NOT NULL,
    CREATOR VARCHAR(20) NOT NULL
);

CREATE TABLE NEW_POSTS (
	ID INT PRIMARY KEY NOT NULL,
    CREATOR VARCHAR(20) NOT NULL,
    LIKES INT NOT NULL
);

INSERT INTO OLD_POSTS (ID, CREATOR) VALUES
(4992, 'dodoru'),
(1192, 'teo'),
(9942, 'guri');

INSERT INTO NEW_POSTS (ID, CREATOR, LIKES) VALUES
(4491, 'dogugu', 12),
(10003, 'william', 1),
(10005, 'teo', 33),
(30042, 'felix', 13),
(40013, 'jerome', 55);

SELECT * FROM OLD_POSTS;
SELECT * FROM NEW_POSTS;

SELECT ID
     , CREATOR
     , 0 AS LIKES
FROM OLD_POSTS

UNION ALL 

SELECT *
FROM NEW_POSTS

ORDER BY 1 DESC