WITH cnt AS (
    SELECT ALGORITHM_TYPE
        , COUNT(*) AS cnt
    FROM PROBLEMS
    GROUP BY ALGORITHM_TYPE
)

SELECT ALGORITHM_TYPE
FROM (
	SELECT ALGORITHM_TYPE
	     , cnt
	FROM cnt
	ORDER BY 2 DESC,1 ASC
	LIMIT 1
) a