USE programmers_mockTest;

CREATE TABLE PROBLEMS (
	ID INT PRIMARY KEY NOT NULL,
    CREATOR VARCHAR(20) NOT NULL,
    ALGORITHM_TYPE VARCHAR(20) NOT NULL
);

INSERT INTO PROBLEMS (ID, CREATOR, ALGORITHM_TYPE) VALUES 
(118, '	Dodori', 'dfs'),
(1334, 'Green', 'hash'),
(5883, 'Green', 'greedy'),
(6889, 'Teo', 'graph'),
(8894, 'Felix', 'dfs');

SELECT * FROM PROBLEMS;

WITH SB AS (
    SELECT 
        ALGORITHM_TYPE, 
        COUNT(*) AS CNT
    FROM PROBLEMS
    GROUP BY ALGORITHM_TYPE
    ORDER BY 2 DESC, 1 ASC
    LIMIT 1
)

SELECT
    ALGORITHM_TYPE
FROM SB 