-- ver1
SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
    SELECT 
        FISH_TYPE, 
        MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY 1
)
ORDER BY 1; 

-- ver2
WITH MF AS (
    SELECT 
        FI.ID,
        FNI.FISH_NAME,
        FI.FISH_TYPE,
        FI.LENGTH,
        MAX(FI.LENGTH) OVER (PARTITION BY FI.FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FNI USING (FISH_TYPE)
)
SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM MF
WHERE LENGTH = MAX_LENGTH
ORDER BY 1;

-- ver3
WITH MF AS (
    SELECT 
        FI.ID,
        FNI.FISH_NAME,
        FI.FISH_TYPE,
        FI.LENGTH,
        ROW_NUMBER() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS RN
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FNI USING (FISH_TYPE)
)
SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM MF
WHERE RN = 1
ORDER BY ID;