-- ver1
SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (
    SELECT 
        FISH_TYPE, 
        MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY 1
)
ORDER BY 1; 

-- ver2
WITH MAX_FISH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY 1
)

SELECT 
    ID, 
    FISH_NAME, 
    LENGTH
FROM MF, FISH_NAME_INFO FI
WHERE MF.FISH_TYPE = FI.FISH_TYPE
ORDER BY 1; 