SELECT 
    SCORE,
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM (
    SELECT 
        EMP_NO, 
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) 
JOIN HR_EMPLOYEES USING (EMP_NO)
ORDER BY 1 DESC
LIMIT 1;