WITH RENT_COUNT AS (
    SELECT 
        CAR_ID,
        COUNT(*) AS TOTAL_RENT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 1
    HAVING COUNT(*) >= 5
)

SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN RENT_COUNT USING (CAR_ID)
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 1, 2
ORDER BY 1 ASC, 2 DESC;