-- ver1
SELECT 
    CAR_ID,
    MAX(
        CASE
            WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
            ELSE '대여 가능'
        END
    ) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC;

-- ver2
SELECT 
    CAR_ID,
    MAX(
        IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능')
    ) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;