WITH SB AS (
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT  
    USER_ID,
    NICKNAME,
    TOTAL_SALES
FROM USED_GOODS_USER U
JOIN SB S ON U.USER_ID = S.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY 3 ASC;