WITH SB AS (
    SELECT
        ID,
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        SIZE_OF_COLONY,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE
    FROM ECOLI_DATA
)
SELECT
    YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM SB
ORDER BY 1, 2;