USE programmers_sum_max_min;

CREATE TABLE ITEM_INFO (
    ITEM_ID INTEGER PRIMARY KEY NOT NULL,
    ITEM_NAME VARCHAR(20) NOT NULL,
    RARITY VARCHAR(20) NOT NULL,
    PRICE INTEGER NOT NULL
);

SHOW TABLES;

INSERT INTO ITEM_INFO (ITEM_ID, ITEM_NAME, RARITY, PRICE)
VALUES 
    (0, 'ITEM_A', 'COMMON', 10000),
    (1, 'ITEM_B', 'LEGEND', 9000),
    (2, 'ITEM_C', 'LEGEND', 11000),
    (3, 'ITEM_D', 'UNIQUE', 10000),
    (4, 'ITEM_E', 'LEGEND', 12000);

SELECT * FROM ITEM_INFO;

SELECT 
	SUM(PRICE) AS TOTAL_PRICE
FROM
	ITEM_INFO
GROUP BY RARITY
HAVING RARITY = 'LEGEND';
