WITH SB AS (
    SELECT COUNT(DISTINCT USER_ID) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT 
    YEAR(O.SALES_DATE) AS year,
    MONTH(O.SALES_DATE) AS month,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / SB.TOTAL_USERS, 1) AS PURCHASE_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U USING (USER_ID)
CROSS JOIN SB
WHERE YEAR(U.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2;