WITH RECURSIVE RC AS (
	SELECT 0 AS HOUR
	UNION ALL
    SELECT HOUR + 1
	FROM RC
	WHERE HOUR < 23
)

SELECT 
	RC.HOUR AS HOUR,
    COUNT(AO.DATETIME) AS COUNT
FROM RC
LEFT JOIN ANIMAL_OUTS AO
    ON RC.HOUR = HOUR(AO.DATETIME)
GROUP BY 1
ORDER BY 1;