SELECT
    P.PRODUCT_ID,
    PRODUCT_NAME,
    (PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER USING (PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY 2
ORDER BY 3 DESC, 1 ASC