WITH REVIEW_COUNTS AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_COUNT AS (
    SELECT MAX(CNT) AS MAX_CNT
    FROM REVIEW_COUNTS
)
SELECT 
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R USING (MEMBER_ID)
JOIN REVIEW_COUNTS C USING (MEMBER_ID)
JOIN MAX_COUNT M ON C.CNT = M.MAX_CNT
ORDER BY 3, 2;