WITH FH AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), 
J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM JULY
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM FH 
JOIN J USING (FLAVOR)
GROUP BY 1
ORDER BY (FH.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3