WITH SB AS (
    SELECT 
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단','SUV')
      AND CAR_ID IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          GROUP BY CAR_ID
          HAVING MAX(END_DATE) <= '2022-11-01'
      )
)
SELECT 
    SB.CAR_ID,
    SB.CAR_TYPE, 
    ROUND(SB.DAILY_FEE * (1 - A.DISCOUNT_RATE * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN A
JOIN SB USING (CAR_TYPE)
WHERE A.DURATION_TYPE LIKE '%30%'
  AND (SB.DAILY_FEE * (1 - A.DISCOUNT_RATE * 0.01) * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;