WITH RECURSIVE GENERATION AS (
    SELECT 
        ID, 
        1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT 
        E.ID, 
        G.DEPTH + 1 AS DEPTH
    FROM ECOLI_DATA E
    JOIN GENERATION G ON E.PARENT_ID = G.ID
)
SELECT 
    COUNT(*) AS COUNT, 
    DEPTH AS GENERATION
FROM GENERATION G
LEFT JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY 2
ORDER BY 2;