USE programmers_groupBy;

SHOW TABLES;

SELECT * FROM BOOK;
SELECT * FROM BOOK_SALES;

CREATE TABLE AUTHOR (
	AUTHOR_ID INTEGER PRIMARY KEY NOT NULL,
    AUTHOR_NAME VARCHAR(20) NOT NULL
);

INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES 
(1, '홍길동'),
(2, '김영호');

SELECT * FROM AUTHOR;

WITH SB AS (
    SELECT 
        B.AUTHOR_ID, 
        B.CATEGORY, 
        SUM(SALES * PRICE) AS TOTAL_SALES
    FROM 
        BOOK_SALES BS
    JOIN 
        BOOK B ON BS.BOOK_ID = B.BOOK_ID
    WHERE 
        BS.SALES_DATE LIKE '2022-01%'
    GROUP BY 
        B.AUTHOR_ID, B.CATEGORY
)

SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    SB.CATEGORY,
    SB.TOTAL_SALES
FROM 
    AUTHOR A
JOIN 
    SB ON A.AUTHOR_ID = SB.AUTHOR_ID
ORDER BY 
    A.AUTHOR_ID ASC, SB.CATEGORY DESC;